/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dibya
 */
import javax.swing.JOptionPane;
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());
    int turn = 2;
    int buttonused[]={0,0,0,0,0,0,0,0,0};
    
    int p1won[]={0,0,0,0,0,0,0,0,0};
    int p2won[]={0,0,0,0,0,0,0,0,0};
    
    int p1won(){
        if(p1won[0]==1 && p1won[1]==1 && p1won[2]==1)
        {
            return 1;
        }
         if(p1won[3]==1 && p1won[4]==1 && p1won[5]==1)
        {
            return 1;
        }
          if(p1won[6]==1 && p1won[7]==1 && p1won[8]==1)
        {
            return 1;
        }
           if(p1won[0]==1 && p1won[3]==1 && p1won[6]==1)
        {
            return 1;
        }
            if(p1won[1]==1 && p1won[4]==1 && p1won[7]==1)
        {
            return 1;
        }
             if(p1won[2]==1 && p1won[5]==1 && p1won[8]==1)
        {
            return 1;
        }
              if(p1won[0]==1 && p1won[4]==1 && p1won[8]==1)
        {
            return 1;
        }
               if(p1won[2]==1 && p1won[4]==1 && p1won[6]==1)
        {
            return 1;
        }
               return 0;
    }
    int p2won() {
    if(p2won[0]==1 && p2won[1]==1 && p2won[2]==1) {
        return 1;
    }
    if(p2won[3]==1 && p2won[4]==1 && p2won[5]==1) {
        return 1;
    }
    if(p2won[6]==1 && p2won[7]==1 && p2won[8]==1) {
        return 1;
    }
    if(p2won[0]==1 && p2won[3]==1 && p2won[6]==1) {
        return 1;
    }
    if(p2won[1]==1 && p2won[4]==1 && p2won[7]==1) {
        return 1;
    }
    if(p2won[2]==1 && p2won[5]==1 && p2won[8]==1) {
        return 1;
    }
    if(p2won[0]==1 && p2won[4]==1 && p2won[8]==1) {
        return 1;
    }
    if(p2won[2]==1 && p2won[4]==1 && p2won[6]==1) {
        return 1;
    }
    return 0;
}

    int isDraw() {
    for (int i = 0; i < 9; i++) {
        if (buttonused[i] == 0) {
            return 0; 
        }
    }
    return 1; 
}
    
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));

        b1.setBackground(new java.awt.Color(255, 204, 255));
        b1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 102, 102));
        b1.addActionListener(this::b1ActionPerformed);

        b4.setBackground(new java.awt.Color(255, 204, 255));
        b4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        b4.setForeground(new java.awt.Color(255, 102, 102));
        b4.addActionListener(this::b4ActionPerformed);

        b7.setBackground(new java.awt.Color(255, 204, 255));
        b7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        b7.setForeground(new java.awt.Color(255, 102, 102));
        b7.addActionListener(this::b7ActionPerformed);

        b5.setBackground(new java.awt.Color(255, 204, 255));
        b5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        b5.setForeground(new java.awt.Color(255, 102, 102));
        b5.addActionListener(this::b5ActionPerformed);

        b2.setBackground(new java.awt.Color(255, 204, 255));
        b2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 102, 102));
        b2.addActionListener(this::b2ActionPerformed);

        b8.setBackground(new java.awt.Color(255, 204, 255));
        b8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        b8.setForeground(new java.awt.Color(255, 102, 102));
        b8.addActionListener(this::b8ActionPerformed);

        b6.setBackground(new java.awt.Color(255, 204, 255));
        b6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        b6.setForeground(new java.awt.Color(255, 102, 102));
        b6.addActionListener(this::b6ActionPerformed);

        b9.setBackground(new java.awt.Color(255, 204, 255));
        b9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        b9.setForeground(new java.awt.Color(255, 102, 102));
        b9.addActionListener(this::b9ActionPerformed);

        b3.setBackground(new java.awt.Color(255, 204, 255));
        b3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 102, 102));
        b3.addActionListener(this::b3ActionPerformed);

        reset.setBackground(new java.awt.Color(255, 255, 204));
        reset.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 102, 102));
        reset.setText("Play Again");
        reset.addActionListener(this::resetActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reset)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if(buttonused[0]==0){
            if(turn%2==0)
            {
                turn++;
                b1.setText("x");
                buttonused[0]=1;
                p1won[0]=1;
                
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "player 1 has won");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "player 2 has won");
                }
                else if (isDraw() == 1) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Match Draw!");
                }
            }
            else 
            {
                turn++;
                b1.setText("o");
                buttonused[0]=1;
                p2won[0]=1;
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "player 1 has won");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "player 2 has won");
                }
                else if (isDraw() == 1) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Match Draw!");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "This button is used already");
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
       if(buttonused[1]==0){
            if(turn%2==0)
            {
                turn++;
                b2.setText("x");
                buttonused[1]=1;
                p1won[1]=1;
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "player 1 has won");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "player 2 has won");
                }
                else if (isDraw() == 1) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Match Draw!");
                }
            }
            else 
            {
                turn++;
                b2.setText("o");
                buttonused[1]=1;
                p2won[1]=1;
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "player 1 has won");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "player 2 has won");
                }
                else if (isDraw() == 1) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Match Draw!");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "This button is used already");
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if(buttonused[2]==0){
            if(turn%2==0)
            {
                turn++;
                b3.setText("x");
                buttonused[2]=1;
                p1won[2]=1;
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "player 1 has won");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "player 2 has won");
                }
                else if (isDraw() == 1) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Match Draw!");
                }
            }
            else 
            {
                turn++;
                b3.setText("o");
                buttonused[2]=1;
                p2won[2]=1;
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "player 1 has won");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "player 2 has won");
                }
                else if (isDraw() == 1) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Match Draw!");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "This button is used already");
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
       if(buttonused[3]==0){
            if(turn%2==0)
            {
                turn++;
                b4.setText("x");
                buttonused[3]=1;
                p1won[3]=1;
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "player 1 has won");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "player 2 has won");
                }
                else if (isDraw() == 1) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Match Draw!");
                }
            }
            else 
            {
                turn++;
                b4.setText("o");
                buttonused[3]=1;
                p2won[3]=1;
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "player 1 has won");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "player 2 has won");
                }
                else if (isDraw() == 1) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Match Draw!");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "This button is used already");
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        if(buttonused[4]==0){
            if(turn%2==0)
            {
                turn++;
                b5.setText("x");
                buttonused[4]=1;
                p1won[4]=1;
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "player 1 has won");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "player 2 has won");
                }
                else if (isDraw() == 1) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Match Draw!");
                }
            }
            else 
            {
                turn++;
                b5.setText("o");
                buttonused[4]=1;
                p2won[4]=1;
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "player 1 has won");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "player 2 has won");
                }
                else if (isDraw() == 1) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Match Draw!");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "This button is used already");
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        if(buttonused[5]==0){
            if(turn%2==0)
            {
                turn++;
                b6.setText("x");
                buttonused[5]=1;
                p1won[5]=1;
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "player 1 has won");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "player 2 has won");
                }
                else if (isDraw() == 1) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Match Draw!");
                }
            }
            else 
            {
                turn++;
                b6.setText("o");
                buttonused[5]=1;
                p2won[5]=1;
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "player 1 has won");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "player 2 has won");
                }
                else if (isDraw() == 1) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Match Draw!");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "This button is used already");
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if(buttonused[6]==0){
            if(turn%2==0)
            {
                turn++;
                b7.setText("x");
                buttonused[6]=1;
                p1won[6]=1;
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "player 1 has won");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "player 2 has won");
                }
                else if (isDraw() == 1) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Match Draw!");
                }
            }
            else 
            {
                turn++;
                b7.setText("o");
                buttonused[6]=1;
                p2won[6]=1;
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "player 1 has won");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "player 2 has won");
                }
                else if (isDraw() == 1) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Match Draw!");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "This button is used already");
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
       if(buttonused[7]==0){
            if(turn%2==0)
            {
                turn++;
                b8.setText("x");
                buttonused[7]=1;
                p1won[7]=1;
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "player 1 has won");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "player 2 has won");
                }
                else if (isDraw() == 1) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Match Draw!");
                }
            }
            else 
            {
                turn++;
                b8.setText("o");
                buttonused[7]=1;
                p2won[7]=1;
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "player 1 has won");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "player 2 has won");
                }
                else if (isDraw() == 1) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Match Draw!");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "This button is used already");
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        if(buttonused[8]==0){
            if(turn%2==0)
            {
                turn++;
                b9.setText("x");
                buttonused[8]=1;
                p1won[8]=1;
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "player 1 has won");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "player 2 has won");
                }
                else if (isDraw() == 1) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Match Draw!");
                }
            }
            else 
            {
                turn++;
                b9.setText("o");
                buttonused[8]=1;
                p2won[8]=1;
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "player 1 has won");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "player 2 has won");
                }
                else if (isDraw() == 1) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Match Draw!");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "This button is used already");
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
    b1.setText("");
    b2.setText("");
    b3.setText("");
    b4.setText("");
    b5.setText("");
    b6.setText("");
    b7.setText("");
    b8.setText("");
    b9.setText("");
    for (int i = 0; i < 9; i++) {
        buttonused[i] = 0;
        p1won[i] = 0;
        p2won[i] = 0;
    }
    turn = 2;
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
